name: YT-RE
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Example: 19.47.53'
        required: false
        default: 'Auto'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'armeabi-v7a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      DEV:
        description: 'Tool cli'
        required: false
        default: 'Stable'
        type: choice
        options:
          - Stable
          - Develop
      FEATURE:
        description: 'Turn on/off feature on: [-e "feature"], off: [-d "feature"]'
        required: false
        default: '-d "Hide captions button" -d "Hide autoplay button" -d "Playback speed"'
permissions: write-all
jobs:
  build1:
    name: 'Buid root'
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          # kakathic
          . .github/install.sh
          . .github/YT.sh
      - name: Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: YT-RE ${{ env.VER }} ${{ env.Kad }}
          tag_name: K${{ env.V }}${{ env.VER }}
          files: Up/*
          body_path: Log.txt
      - name: Upload Json
        uses: softprops/action-gh-release@v2
        with:
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
  build2:
    name: 'Buid no-root'
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'false'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          # kakathic
          . .github/install.sh
          . .github/YT.sh
      - name: Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: YT-RE ${{ env.VER }} ${{ env.Kad }}
          tag_name: K${{ env.V }}${{ env.VER }}
          files: Up/*
          body_path: Log.txt
  build3:
    name: 'Buid amoled root'
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'true'
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          # kakathic
          . .github/install.sh
          . .github/YT.sh
      - name: Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: YT-RE ${{ env.VER }} ${{ env.Kad }}
          tag_name: K${{ env.V }}${{ env.VER }}
          files: Up/*
          body_path: Log.txt
      - name: Upload Json
        uses: softprops/action-gh-release@v2
        with:
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
  build4:
    name: 'Buid amoled no-root'
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'false'
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          # kakathic
          . .github/install.sh
          . .github/YT.sh
      - name: Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: YT-RE ${{ env.VER }} ${{ env.Kad }}
          tag_name: K${{ env.V }}${{ env.VER }}
          files: Up/*
          body_path: Log.txt
          
